[workspace]
members = ["openbim-mmc"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.88.0"
license = "MIT"
authors = ["openbimrs contributors"]
repository = "https://github.com/openbimrs/mmc"

[workspace.dependencies]
iri-string = { version = "0.7.8", default-features = false }
quick-xml = "0.38.4"
thiserror = "2.0.16"
unicode-normalization = "0.1.24"
uuid = { version = "1.18.1", features = ["std"] }
zip = { version = "4.3.0", default-features = false, features = ["deflate"] }
